server:
  port: 9400

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: micro_payments
      authentication-database: admin
      username: rootuser
      password: rootpass
