my:
  greeting: "GREETING FROM CONFIG SERVER"
  list:
    values: ["1", "2", "3"]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: INFO
